name: HW-4 CD
on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  DB_HOST: localhost:3306
  DB_NAME: db_webapp3
  DB_USERNAME: root
  DB_PASSWORD: 11959791
  BUCKET_NAME: bucket
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: AKIAZFMPCB6SLLLTUPHC
  AWS_SECRET_ACCESS_KEY: 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

jobs:
  build-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: 11959791
          MYSQL_DATABASE: db_webapp3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:
          mvn package

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./ec2.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./ec2.pkr.hcl"

      - name: Run packer build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd packer && packer build ec2.pkr.hcl