name: HW-4 CD
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:
          mvn package

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: "latest"

      - name: Run packer build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd packer && packer build ec2.pkr.hcl