name: HW-4 CI

on:
  pull_request:
    branches:
      - main

jobs:
  hw4-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: CI
        run:
          mvn test