name: HW-4 CI

on:
  pull_request:
    branches:
      - main

env:
  DB_HOST: localhost:3306
  DB_NAME: db_webapp3
  DB_USERNAME: root
  DB_PASSWORD: 11959791
  BUCKET_NAME: bucket_name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: 11959791
          MYSQL_DATABASE: db_webapp3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: CI
        run:
          mvn test