name: hw1-actions

on:
  push:
    branches:
      - hw1
      - main
  pull_request:
    branches:
      - hw1
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: db_webapp3
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: 11959791
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify csye6250db DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW DATABASES LIKE 'db_webapp3'"

      - name: Build with Maven
        run:
          mvn clean install -DskipTests=false
