name: hw1-actions

on:
  push:
    branches:
      - hw1
      - main
  pull_request:
    branches:
      - hw1
      - main
      
env:
  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/db_webapp?useSSL=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: password
      
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: db_webapp
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: All the Tests Checks
        run: mvn clean install
