name: hw1-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_HOST: localhost:3306
  DB_NAME: db_webapp3
  DB_USERNAME: root
  DB_PASSWORD: 11959791
  BUCKET_NAME: bucket
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: AKIAZFMPCB6SLLLTUPHC
  AWS_SECRET_ACCESS_KEY: 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

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: 11959791
          MYSQL_DATABASE: db_webapp3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify  db_webapp3 DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot --password=11959791 -e "SHOW DATABASES LIKE 'db_webapp3'"

      - name: Build with Maven
        run:
          mvn clean install -DskipTests=false

